name: Build on Ubuntu
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{matrix.os}}

    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        os: [ ubuntu-22.04, ubuntu-24.04 ]
        compiler: [ clang++, g++ ]
        generator: [ Ninja, Unix Makefiles ]
        build_type: [ Debug, Release ]
    
    steps:
    - name: Clone
      uses: actions/checkout@v4

    - name: Build
      run: |
        cmake -B build                              \
          -G ${{matrix.generator}}                  \
          -DCMAKE_CXX_COMPILER=${{matrix.compiler}} \
          -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
          -DCME_BUILD_TESTS_C=ON                    \
          -DCME_BUILD_TESTS_CXX=ON
        cmake --build build --parallel