name: Test on Ubuntu
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        generator: [ Ninja, Unix Makefiles ]
        build_type: [ Debug, Release ]
    
    steps:
    - name: Clone
      uses: actions/checkout@v4

    - name: Install Clang 19 and 20
      run: |
        sudo apt-get update && sudo apt-get install lsb-release gpg software-properties-common clang clang-tools
        ln -s /usr/bin/clang-scan-deps-18 usr/local/bin/clang-scan-deps
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 19
        sudo ./llvm.sh 20

    - name: Build and Test
      run: |
        cmake -B build                              \
          -G '${{matrix.generator}}'                \
          -DCMAKE_C_COMPILER=clang-19               \
          -DCMAKE_CXX_COMPILER=clang++-19           \
          -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
          -DCME_BUILD_TESTS_C=ON                    \
          -DCME_BUILD_TESTS_CXX=ON                  \
          -DCME_BUILD_TESTS_CXX_MODULE=ON
        cmake --build build --parallel
        cd build && ctest --output-on-failure

        cd .. && sudo rm -rf build
        cmake -B build                              \
          -G '${{matrix.generator}}'                \
          -DCMAKE_C_COMPILER=clang-20               \
          -DCMAKE_CXX_COMPILER=clang++-20           \
          -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
          -DCME_BUILD_TESTS_C=ON                    \
          -DCME_BUILD_TESTS_CXX=ON                  \
          -DCME_BUILD_TESTS_CXX_MODULE=ON
        cmake --build build --parallel
        cd build && ctest --output-on-failure